[package]
name = "yangfmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.1", features = ["derive"] }
lazy_static = "1.4.0"
pretty_assertions = "1.2.1"
regex = "1.7.3"
textwrap = "0.16"
