[package]
name = "yangfmt_parsing"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
lazy_static.workspace = true
pretty_assertions.workspace = true
regex.workspace = true
textwrap.workspace = true

yangfmt_lexing.workspace = true
