[package]
name = "yangfmt_formatting"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
lazy_static.workspace = true
phf.workspace = true
pretty_assertions.workspace = true
textwrap.workspace = true

yangfmt_parsing.workspace = true
