[package]
name = "yangfmt_lexing"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
lazy_static.workspace = true
pretty_assertions.workspace = true
regex.workspace = true
textwrap.workspace = true
