[package]
name = "yangfmt_lexing"
version = "0.0.0"
authors.workspace = true
edition.workspace = true
license-file.workspace = true

[dependencies]
lazy_static.workspace = true
pretty_assertions.workspace = true
regex.workspace = true
textwrap.workspace = true
