name: Build pipeline
on: push

jobs:
  build-and-test:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
